import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { db } from '../src/db.js';
import { SUBJECTS_META } from '../src/timetable.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.join(__dirname, '..');
const LOGS_DIR = path.join(ROOT_DIR, 'Pvt.Logs');

if (!fs.existsSync(LOGS_DIR)) {
  fs.mkdirSync(LOGS_DIR, { recursive: true });
}

function getTodayString() {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function generateDailySummary(dateStr = getTodayString()) {
  const dayAttendance = db.getDayAttendance(dateStr);
  const stats = db.getCalculatedStats();
  const now = new Date();
  const timestamp = now.toLocaleString('en-US', { timeZone: 'Asia/Kolkata' });

  let md = `# 📊 GTBIT Attendance Daily Summary - ${dateStr}\n\n`;
  md += `**Generated on:** ${timestamp} (IST)  \n`;
  md += `**Day:** ${dayAttendance.dayName}  \n`;
  md += `**Overall Attendance:** **${stats.overall.percentage}%** (${stats.overall.totalPresent}/${stats.overall.totalHeld} classes attended)\n\n`;

  // Status Indicator
  if (stats.overall.percentage < 60) {
    md += `> 🔴 **CRITICAL ALERT:** Overall attendance is below 60%! Urgent attendance required across all upcoming classes.\n\n`;
  } else if (stats.overall.percentage < 75) {
    md += `> 🟡 **WARNING:** Attendance is below GGSIPU 75% standard. Need ${stats.overall.needFor75} classes to hit 75%.\n\n`;
  } else {
    md += `> 🟢 **SAFE ZONE:** Attendance is $\\ge 75%$. You currently have **${stats.overall.safeBunks75} safe bunks** available.\n\n`;
  }

  // 1. Today's Classes Breakdown
  md += `## 📋 Classes for Today (${dayAttendance.dayName}, ${dateStr})\n\n`;
  if (!dayAttendance.slots || dayAttendance.slots.length === 0) {
    md += `*No scheduled classes today (Day off / Weekend).*\n\n`;
  } else {
    md += `| Time | Subject | Teacher | Room | Status |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;
    dayAttendance.slots.forEach((s) => {
      let statusIcon = '⚪ Unmarked';
      if (s.status === 'present') statusIcon = '✅ Present';
      else if (s.status === 'absent') statusIcon = '❌ Absent';
      else if (s.status === 'cancelled') statusIcon = '⛔ Cancelled / Mass Bunk';

      md += `| ${s.time} | **${s.subject}** (${s.type}) | ${s.teacher} | ${s.room} | ${statusIcon} |\n`;
    });
    md += `\n`;
  }

  // 2. Cumulative Subject Breakdown
  md += `## 🎯 Cumulative Subject Breakdown & Recovery Actions\n\n`;
  md += `| Subject | Type | Attended / Held | % | Status | Recommendation / Action |\n`;
  md += `| :--- | :--- | :--- | :--- | :--- | :--- |\n`;

  stats.subjects.forEach((subj) => {
    let statusEmoji = '🟢';
    if (subj.statusCategory === 'red') statusEmoji = '🔴';
    else if (subj.statusCategory === 'yellow') statusEmoji = '🟡';

    md += `| **${subj.code}** | ${subj.type} | ${subj.totalPresent} / ${subj.totalHeld} | **${subj.percentage}%** | ${statusEmoji} | ${subj.advice} |\n`;
  });
  md += `\n`;

  // 3. Urgent Next-Week Strategy
  const critical = stats.subjects.filter((s) => s.statusCategory === 'red');
  if (critical.length > 0) {
    md += `## ⚠️ Critical Action Items for Next Week\n\n`;
    critical.forEach((s) => {
      md += `- **${s.code}** (${s.percentage}%): Must attend **${s.needFor60} consecutive classes** to hit 60% baseline. (${s.weeklyFrequency} classes available next week).\n`;
    });
    md += `\n`;
  }

  md += `---\n*Automated Daily Sync generated by GTBIT Attendance Engine.*\n`;

  // Write files
  const dateFile = path.join(LOGS_DIR, `Summary_${dateStr}.md`);
  const latestFile = path.join(LOGS_DIR, `LATEST_SUMMARY.md`);
  fs.writeFileSync(dateFile, md, 'utf-8');
  fs.writeFileSync(latestFile, md, 'utf-8');

  console.log(`[DailySync] Summary generated at: ${dateFile}`);
  return { dateFile, latestFile };
}

export function runDailyGitPush() {
  console.log('[DailySync] Starting Daily Sync & Git Push...');
  try {
    generateDailySummary();

    // Stage changes
    execSync('git add data/ Pvt.Logs/ public/ src/ server.js package.json package-lock.json README.md', {
      cwd: ROOT_DIR,
      stdio: 'pipe'
    });

    const todayStr = getTodayString();
    const commitMsg = `chore(logs): Daily attendance update & summary for ${todayStr}`;
    
    // Check if there are changes to commit
    const status = execSync('git status --porcelain', { cwd: ROOT_DIR, encoding: 'utf-8' });
    if (status.trim().length > 0) {
      execSync(`git commit -m "${commitMsg}"`, { cwd: ROOT_DIR, stdio: 'pipe' });
      console.log(`[DailySync] Committed: "${commitMsg}"`);
    } else {
      console.log('[DailySync] No new changes to commit.');
    }

    // Push to origin
    try {
      execSync('git push -u origin HEAD', { cwd: ROOT_DIR, stdio: 'pipe' });
      console.log('[DailySync] Successfully pushed daily update to GitHub repository!');
    } catch (pushErr) {
      console.error('[DailySync] Git push failed (may need authentication or branch setup):', pushErr.message);
    }
  } catch (err) {
    console.error('[DailySync] Error during daily sync:', err);
  }
}

// Run directly if called as a script
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runDailyGitPush();
}
